version: "3"

services:
  web:
    build: web/.
    ports:
      - "80:80"
    networks:
     - webnet
    volumes:
     - /var/www/html:/var/www/html
 
  db:
    build: db/.
    restart: on-failure
    ports:
      - "3306"
    env_file: 
       - "db/db.env"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    networks:
      - webnet

  ssh:
    build: ssh/.
    restart: on-failure
    ports:
      - "2222:22"
    networks:
      - webnet


  radius:
    build: radius/.
    ports:
      - "1812:1812"
      - "1813:1813"
      - "18120:18120"
    networks:
      - webnet



  log:
    build: log/.
    ports:
      - "514:514"
    networks:
      - webnet
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro


networks:
  webnet:

volumes:
  webvolume:  
